apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: z4ougmby5-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:ebb538eb4ad996f92b62aa3f213dcb447fc3d032@sha256:ea57f90ec2d7c5ed6149b09b4ae8bbf4d073812cf1b9bd6ea9826c91ecbcfb22
          name: container-image
